steps:

# Install node packages
  - name: node:16
    entrypoint: npm
    args: [ 'install']

  # Build productive files - ng build
  - name: node:16
    entrypoint: npm
    args: [ 'run', 'build', '--prod']

    # Deploy to google cloud app egnine
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', '--version=prod']
